###############################################################################################
# git-version.yml
###############################################################################################

# this step calls GitVersion to calculate the sematic version based on GIT tags 

steps:
  - task: GitVersion@5
    displayName: 'GitVersion'
    inputs:
      #updateAssemblyInfo: true
      preferBundledVersion: false

  - bash: |
      echo "Major:                           $(GitVersion.Major)"
      echo "Minor:                           $(GitVersion.Minor)"
      echo "Patch:                           $(GitVersion.Patch)"
      echo "PreReleaseTag:                   $(GitVersion.PreReleaseTag)"
      echo "PreReleaseTagWithDash:           $(GitVersion.PreReleaseTagWithDash)"
      echo "PreReleaseLabel:                 $(GitVersion.PreReleaseLabel)"
      echo "PreReleaseNumber:                $(GitVersion.PreReleaseNumber)"
      echo "BuildMetaData:                   $(GitVersion.BuildMetaData)"
      echo "BuildMetaDataPadded:             $(GitVersion.BuildMetaDataPadded)"
      echo "FullBuildMetaData:               $(GitVersion.FullBuildMetaData)"
      echo "MajorMinorPatch:                 $(GitVersion.MajorMinorPatch)"
      echo "SemVer:                          $(GitVersion.SemVer)"
      echo "LegacySemVer:                    $(GitVersion.LegacySemVer)"
      echo "LegacySemVerPadded:              $(GitVersion.LegacySemVerPadded)"
      echo "AssemblySemVer:                  $(GitVersion.AssemblySemVer)"
      echo "AssemblySemFileVer:              $(GitVersion.AssemblySemFileVer)"
      echo "FullSemVer:                      $(GitVersion.FullSemVer)"
      echo "InformationalVersion:            $(GitVersion.InformationalVersion)"
      echo "BranchName:                      $(GitVersion.BranchName)"
      echo "Sha:                             $(GitVersion.Sha)"
      echo "ShortSha:                        $(GitVersion.ShortSha)"
      echo "NuGetVersionV2:                  $(GitVersion.NuGetVersionV2)"
      echo "NuGetVersion:                    $(GitVersion.NuGetVersion)"
      echo "NuGetPreReleaseTagV2:            $(GitVersion.NuGetPreReleaseTagV2)"
      echo "NuGetPreReleaseTag:              $(GitVersion.NuGetPreReleaseTag)"
      echo "CommitsSinceVersionSource:       $(GitVersion.CommitsSinceVersionSource)"
      echo "CommitsSinceVersionSourcePadded: $(GitVersion.CommitsSinceVersionSourcePadded)"
      echo "CommitDate:                      $(GitVersion.CommitDate)"
    displayName: 'Log GitVersion variables'
