###############################################################################################
# build-dependencies-steps.yml
###############################################################################################

# this set of steps builds the solution, running:
# - dotnet restore
# - dotnet build --no-restore
# - dotnet publish --no-build

parameters:
  buildConfiguration:   'Release'
  apiName:              ''

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet dependencies'
    inputs:
      command: 'restore'
      projects: './${{ parameters.apiName }}.sln'
      feedsToUse: 'config'
      nugetConfigPath: './NuGet.Config'
      
  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: 'build'
      projects: './${{ parameters.apiName }}.sln'
      arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'

  - task: DotNetCoreCLI@2
    displayName: 'Publish API binaries'
    inputs:
      command: 'publish'
      projects: './${{ parameters.apiName }}.sln'
      zipAfterPublish: false
      publishWebProjects: true
      arguments: '--no-build --configuration ${{ parameters.buildConfiguration }}'
