###############################################################################################
# build-dependencies-steps.yml
###############################################################################################

# this set of steps installs all dependencies needed by the build, such as:
# - custom .NET Core SDK (if preview, which is not installed by default on the build agent)
# - jq command line utility (needed for editing swagger.json)
# - creating links from the preview SDK to other installed SDKs (for backwards compatibility,
#  needed by some utilities such as swagger dotnet CLI generation tool)

parameters:
  customDotnetVersion: ""

steps:
  # this is installed by default on the Azure Ubuntu build agent
  #- bash: sudo apt-get install jq
  # displayName: 'Installing build dependency: jq'

  # - bash: sudo apt-get install tree
  #   displayName: "Installing various utilities from Ubuntu apt repo"

  - template: "step.install-custom-sdk.yml"
    parameters:
      sdk: "${{ parameters.customDotnetVersion }}"

  # create links to .NET Core Runtimes from v. 2.2 because it is needed by 'dotnet swagger' CLI
  - bash: ln -s /usr/share/dotnet/shared/Microsoft.NETCore.App/2.2.?/ $(dirname `which dotnet`)/shared/Microsoft.NETCore.App
    displayName: "Create link to NETCoreApp 2.2 runtime (for dotnet CLI 3.0)"
  - bash: ln -s /usr/share/dotnet/shared/Microsoft.AspNetCore.App/2.2.?/ $(dirname `which dotnet`)/shared/Microsoft.AspNetCore.App
    displayName: "Create link to AspNetCore 2.2 runtime (for dotnet CLI 3.0)"
