parameters:
  variableName: ''

steps:
  - bash: |
      ls -la $(Pipeline.Workspace)/variables
      cat $(Pipeline.Workspace)/variables/${{ parameters.variableName }}
      export VARIABLE=`cat $(Pipeline.Workspace)/variables/${{ parameters.variableName }}`
      echo ${{ parameters.variableName }} is $VARIABLE
      echo '##vso[task.setvariable variable=${{ parameters.variableName }};]'$VARIABLE
    displayName: 'Retrieve ${{ parameters.variableName }}'

  - bash: echo Retrieved variable ${{ parameters.variableName }}
    displayName: 'Log ${{ parameters.variableName }} $(${{ parameters.variableName }})'
